#!/usr/bin/env python3
"""Regenerate supabase/seed_adherence.sql from legacy/data/adherence_history.json.

The JSON (built 2026-06-12 from the Time is Money sheet matched against the
calendar) is the source of truth; the schedule_adherence_history table is a
derived copy so admin_schedule_adherence can put the baseline beside the live
tracker-era numbers. Rows without a usable arrival delta are skipped, same as
the report's stats.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((ROOT / 'legacy' / 'data' / 'adherence_history.json').read_text())
rows = data.get('rows', [])


def lit(v):
    if v is None:
        return 'null'
    if isinstance(v, (int, float)):
        return str(int(v))
    return "'" + str(v).replace("'", "''") + "'"


values = []
for r in rows:
    if not r.get('matched') or r.get('arrival_delta_min') is None:
        continue
    # Deltas beyond 6 hours are sheet anomalies, excluded from stats in the
    # report; keep the table consistent with the report.
    if abs(r['arrival_delta_min']) > 360:
        continue
    values.append('(%s, %s, %s, %s, %s, %s)' % (
        lit(r['date']), lit(r['client']), lit(r['arrival_delta_min']),
        lit(r.get('left_delta_min')), lit(r.get('on_site_min')),
        lit(r.get('stop_index'))))

out = ROOT / 'supabase' / 'seed_adherence.sql'
header = (
    '-- Generated by scripts/gen_adherence_seed.py from '
    'legacy/data/adherence_history.json. Do not edit by hand.\n'
    'truncate public.schedule_adherence_history;\n'
)
chunks = []
for i in range(0, len(values), 200):
    chunks.append(
        'insert into public.schedule_adherence_history '
        '(day, client, delta_min, left_delta_min, on_site_min, stop_index) values\n'
        + ',\n'.join(values[i:i + 200]) + ';\n')
out.write_text(header + '\n'.join(chunks))
print('wrote', out, 'with', len(values), 'rows')
