#!/usr/bin/env python3
"""Generate supabase/seed.sql from data/clients.json (the source of truth).

The client book lives in data/clients.json. This script turns it into an
idempotent SQL seed: it clears the tables and re-inserts every record, so
re-running it fully refreshes Clean's database from the authoritative file.

Run: python3 scripts/gen_seed_sql.py   (writes supabase/seed.sql)
"""

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CLIENTS = REPO / "data" / "clients.json"
OUT = REPO / "supabase" / "seed.sql"


def q(val):
    """SQL literal for a nullable string/number."""
    if val is None:
        return "null"
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, (int, float)):
        return str(val)
    return "'" + str(val).replace("'", "''") + "'"


def arr(values):
    """SQL text[] literal."""
    if not values:
        return "'{}'"
    inner = ", ".join("'" + str(v).replace("'", "''") + "'" for v in values)
    return "array[" + inner + "]"


def jsonb(obj):
    if not obj:
        return "'{}'::jsonb"
    return "'" + json.dumps(obj).replace("'", "''") + "'::jsonb"


def price_cents(dollars):
    if dollars is None:
        return "null"
    return str(int(round(dollars * 100)))


def client_row(c, roster_group):
    loc = c.get("location") or {}
    # Non-standing records carry a flat address/zone rather than a location object.
    address = loc.get("address") if loc else c.get("address")
    zone = loc.get("zone") if loc else c.get("zone")
    avail = c.get("availability") or {}
    note = c.get("note") or c.get("reason")
    routed = c.get("routed", roster_group == "standing")
    cols = [
        ("name", q(c.get("name"))),
        ("aka", q(c.get("aka"))),
        ("roster_group", q(roster_group)),
        ("status", q(c.get("status"))),
        ("service_type", q(c.get("service_type"))),
        ("cadence_days", q(c.get("cadence_days"))),
        ("cadence_confidence", q(c.get("cadence_confidence"))),
        ("cadence_note", q(c.get("cadence_note"))),
        ("hardness", q(c.get("hardness"))),
        ("location_address", q(address)),
        ("location_zip", q(loc.get("zip"))),
        ("location_zone", q(zone)),
        ("location_plus", q(loc.get("plus"))),
        ("location_geo_notes", q(loc.get("geo_notes"))),
        ("access", jsonb(c.get("access"))),
        ("availability_hard", q(avail.get("hard"))),
        ("availability_soft", q(avail.get("soft"))),
        ("availability_not_days", arr(avail.get("not_days"))),
        ("availability_seasonal", q(avail.get("seasonal"))),
        ("flags", arr(c.get("flags"))),
        ("relationships", arr(c.get("relationships"))),
        ("data_gaps", arr(c.get("data_gaps"))),
        ("routed", q(bool(routed))),
        ("exclude_from_everything", q(bool(c.get("exclude_from_everything", False)))),
        ("note", q(note)),
    ]
    names = ", ".join(name for name, _ in cols)
    vals = ", ".join(val for _, val in cols)
    return f"insert into public.clients ({names})\n  values ({vals});"


def dog_rows(c):
    out = []
    for d in c.get("dogs", []) or []:
        out.append(
            "insert into public.dogs (client_id, name, breed, price_cents, notes)\n"
            "  values ((select id from public.clients where name = "
            f"{q(c['name'])}), {q(d.get('name'))}, {q(d.get('breed'))}, "
            f"{price_cents(d.get('price'))}, {q(d.get('notes'))});"
        )
    return out


def main():
    data = json.loads(CLIENTS.read_text())
    lines = [
        "-- GENERATED by scripts/gen_seed_sql.py from data/clients.json. Do not edit by hand.",
        "-- Re-run the generator to refresh from the source of truth.",
        "begin;",
        "delete from public.dogs;",
        "delete from public.clients;",
        "",
    ]
    for group in ("standing", "one_off", "at_will", "banned"):
        records = data.get(group, [])
        lines.append(f"-- {group} ({len(records)})")
        for c in records:
            lines.append(client_row(c, group))
        lines.append("")
    lines.append("-- dogs")
    for group in ("standing", "one_off", "at_will", "banned"):
        for c in data.get(group, []):
            lines.extend(dog_rows(c))
    lines.append("")
    lines.append("commit;")
    lines.append("")
    OUT.write_text("\n".join(lines))
    n_clients = sum(len(data.get(g, [])) for g in ("standing", "one_off", "at_will", "banned"))
    n_dogs = sum(len(c.get("dogs", []) or []) for g in ("standing",) for c in data.get(g, []))
    print(f"wrote {OUT.relative_to(REPO)}: {n_clients} clients, {n_dogs} dogs")


if __name__ == "__main__":
    main()
